### ISSUE TITLE
Update to bring in line with current philosophy of tlosint-vm

### ISSUE THREAD

**Issue by humandecoded** [tracelabs/Trace-Labs-VM-M1-Mac-Build#2]
Made lots of changes in the design philosophy of the VM, while there is currently not a way to generate VMs for M1 macs (debos doesn't support arm) we can still mirror the structure of those VMS in the M1 version

* remove tools from build process
* update bookmards
* create script to install tools if desired
* remove update script
* push more frequent releases
* can we host on Github?

**Comment by humandecoded** [comment]
So before, we could leverage my issue here: 
https://gitlab.com/kalilinux/build-scripts/live-build-config/-/issues/44
To create a live iso with the option to install. The build is currently working but the "Install" option gives
an error stating the kernel must be loaded first, historically this has worked so not sure what changed

Maybe explore a script that will "Trace Labs-ify" an existing Kali distro instead of creating one from scratch?

**Comment by humandecoded** [comment]
Update. The existing installer DOES work but you have to choose:
Advanced Install Options -> Text Installer -> Install

**Comment by mmuyskens** [comment]
Few things to note about above (as far as UTM at least)

When going to "Advanced Install Options -> Text Installer -> Install" - you will get no output. You need to add a serial device to the VM, at least for the duration of the install. (https://prnt.sc/nDy48T-O0sz1) - It's the same Kali / UTM issue mentioned here; https://docs.getutm.app/guides/kali/

**Comment by humandecoded** [comment]
last step here will be adding ability to build in docker and then use github actions to build and host realeases

**Comment by humandecoded** [comment]
addressed with #13 , final step will be github actions that build the iso on release
